# Generated by Django 4.1.4 on 2023-01-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detailmodel',
            table='detailmodel',
        ),
    ]
