# Generated by Django 4.1.3 on 2023-01-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_acount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
